apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ml-demo

resources:
  - link-github.yaml
  - namespace.yaml


  - label-studio/overlays/flyingthings
  - components/minio
  - components/yolo-api/base
