---
apiVersion: argoproj.io/v1beta1
kind: Application
metadata:
  name: flyingthings-ml-demo-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: ml-demo
    server: https://kubernetes.default.svc
  project: flyingthings-config
  source:
    path: components/ml-demo
    repoURL: https://github.com/gfulton-redhat/flyingthings
    targetRevision: HEAD
  syncPolicy:
    preserveResourcesOnDeletion: false
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---