---
apiVersion: argoproj.io/v1beta1
kind: AppProject
metadata:
  name: flyingthings-config
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
  sourceNamespaces:
    - ml-demo
---