apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ml-model
spec:
  entrypoint: source-checkout
  templates:
  - name: source-checkout
    inputs:
      artifacts:
      # Check out the main branch of the argo repo and place it at /src
      # revision can be anything that git checkout accepts: branch, commit, tag, etc.
      - name: argo-source
        path: /src
        git:
          repo: https://github.com/gfulton-redhat/flyingthings.git
          revision: "main"
      - name: print
        arguments:
          parameters:
            - name: message
                value: "{{steps.generate.outputs.result}}"  # The result of the here-script
      container:
        image:  ubi9:latest
        command: [sh, -c]
        args: ["echo result was: {{inputs.parameters.message}}"]
