apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: ml-model
spec:
  entrypoint: source-checkout
  templates:
  - name: source-checkout
    steps:
    - - name: git-clone
        template: git-clone
        arguments:
          parameters:
            - name: GIT_URL
              value: https://github.com/gfulton-redhat/flyingthings.git
            - name: GIT_REVISION
              value: main
#    - name: git-clone
#      script:
#        image: quay.io/openshift-pipeline/openshift-pipelines-git-init:5.0
#        command: [bash]
#        source: |                                         # Contents of the here-script
#          git clone -b {{inputs.parameters.GIT_REVISION}} {{inputs.parameters.GIT_URL}}
    - name: git-clone
      inputs:
        parameters:
          - name: GIT_URL
          - name: GIT_REVISION
      script:
        image: quay.io/openshift-pipeline/openshift-pipelines-git-init:5.0
        command: [bash]
        source: |                                         # Contents of the here-script
          git clone -b {{inputs.parameters.GIT_REVISION}} {{inputs.parameters.GIT_URL}}