---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flyingthings-operators-apps
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: flyingthings-config
  source:
    path: gitops
    repoURL: https://github.com/gfulton-redhat/flyingthings
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
---
