---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: flyingthings-pipelines-app
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io/background
spec:
  destination:
    namespace: ml-demo
    server: https://kubernetes.default.svc
  project: flyingthings-project
  source:
    path: components/pipelines
    repoURL: https://github.com/gfulton-redhat/flyingthings
    targetRevision: main
  syncPolicy:
    preserveResourcesOnDeletion: false
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
---