apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - operators
  - operators-configs



patches:
  - target:
      kind: ConsoleNotification
      name: banner-demo
    patch: |-
      - op: replace
        path: /spec/text
        value: 'DEMO: Flyingthings on OpenShift w/ GPUs'
